### ISSUE TITLE
getvar fails when meta=True

### ISSUE THREAD

**Issue by CameronMcAinsh** [NCAR/wrf-python#126]
I have been working on an dataset on which getvar and all other functions work perfectly. But I have recently received a new dataset which is giving me issues when calling the getvar function with metadata set to true. I'm thinking it has something to do with the order of coordinates, or the use of XTIME in the place of Time.

**The OLD dataset looks like this:**

Dimensions:                (Time: 1, bottom_top: 49, bottom_top_stag: 50, soil_layers_stag: 6, south_north: 108, south_north_stag: 109, west_east: 108, west_east_stag: 109)
Coordinates:
    XLAT                   (Time, south_north, west_east) float32 ...
    XLONG                  (Time, south_north, west_east) float32 ...
    XTIME                  (Time) datetime64[ns] ...
    XLAT_U                 (Time, south_north, west_east_stag) float32 ...
    XLONG_U                (Time, south_north, west_east_stag) float32 ...
    XLAT_V                 (Time, south_north_stag, west_east) float32 ...
    XLONG_V                (Time, south_north_stag, west_east) float32 ...

**While the NEW dataset is this:**

Dimensions:                (XTIME: 1, bottom_top: 49, bottom_top_stag: 50, soil_layers_stag: 6, south_north: 108, south_north_stag: 109, west_east: 108, west_east_stag: 109)
Coordinates:
  * XTIME                  (XTIME) datetime64[ns] 2015-01-01
    XLONG                  (south_north, west_east) float32 ...
    XLAT                   (south_north, west_east) float32 ...
    XLONG_U                (south_north, west_east_stag) float32 ...
    XLAT_U                 (south_north, west_east_stag) float32 ...
    XLONG_V                (south_north_stag, west_east) float32 ...
    XLAT_V                 (south_north_stag, west_east) float32 ...

So for example:
IN: Q_rain = getvar(NEW, "QRAIN")

OUT: Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 5, in <module>
  File "/usr/local/lib/python3.8/dist-packages/wrf/routines.py", line 336, in getvar
    return extract_vars(wrfin, timeidx, varname, 
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 2278, in extract_vars
    return {var:_extract_var(wrfin, var, timeidx, None,
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 2278, in <dictcomp>
    return {var:_extract_var(wrfin, var, timeidx, None,
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 2204, in _extract_var
    is_moving = is_moving_domain(wrfin, varname, _key=_key)
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 793, in is_moving_domain
    if _corners_moved(first_wrfnc, ll_corner, ur_corner, lat_coord, lon_coord):
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 663, in _corners_moved
    for i in py3range(lats.shape[-3]):
**IndexError: tuple index out of range**

Any ideas as to what the problem is? 
Or if it is possible to re-write the NEW file with the same structure as the OLD file?

Thank you to anyone that can help me!

**Comment by michaelavs** [comment]
I think you are correct that the `XTIME` variable is causing the problem. I was looking at the [table of available diagnostics](https://wrf-python.readthedocs.io/en/latest/diagnostics.html?highlight=xtime#table-of-available-diagnostics), and it would appear that the XTIME variable would be in reference to the model run time while `Time` variable is part of the data. Did anything change in how the data is read in? Or in the namelist.input file, perhaps?

**Comment by CameronMcAinsh** [comment]
The variable definitions are the following:
OLD (WORKING):

> Variables:

    Times                
           Size:       19x1
           Dimensions: DateStrLen,Time
           Datatype:   char

  And XTIME is not defined as a data variable, just as a coordinate for other variables.



NEW (NOT WORKING)

> Variables:

    XTIME                
           Size:       1x1
           Dimensions: XTIME
           Datatype:   single
           Attributes:
                       standard_name = 'time'
                       units         = 'minutes since 2015-01-01 00:00:00'
                       calendar      = 'standard'
                       axis          = 'T'

  And Times is not defined as a variable.

Maybe it helps to know that the OLD data set I was using was a single file, a "snapshot". While the NEW is part of a sequence of files for a whole day, with time step of 1 minute, so 1440 files.  Or that the format is different (64bit and netcfd4_classic respectively). 

Thank you so much for the help.

**Comment by michaelavs** [comment]
Currently, my best guess is that each file will need to be read in separately and then have variables taken from it, but that doesn't fully explain what is causing the issue with missing `QRAIN` variable. `tuple index out of range` implies that the variable you are looking for does not exist in the data set. Can you confirm that the variable is present in your file by just doing `print(NEW)`? And also post the lines you are using to call the data and the variable?

**Comment by CameronMcAinsh** [comment]
Yes, I confirm that QRAIN (and all other variables) are in the NEW file. Currently I am reading the variables with meta set to False and creating the xarray myself, but I would prefer to use the full functionality of the getvar and skip the step of manually adding the meta data. So this is the code:
```
from netCDF4 import Dataset
from wrf import getvar
ncfile = Dataset("/wrfout_d03_2015-01-01_00%3A00%3A00")
QRAIN = getvar(ncfile, "QRAIN", meta=False)

```
and the error message is the following: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 4, in <module>
  File "/usr/local/lib/python3.8/dist-packages/wrf/routines.py", line 336, in getvar
    return extract_vars(wrfin, timeidx, varname, 
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 2278, in extract_vars
    return {var:_extract_var(wrfin, var, timeidx, None,
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 2278, in <dictcomp>
    return {var:_extract_var(wrfin, var, timeidx, None,
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 2204, in _extract_var
    is_moving = is_moving_domain(wrfin, varname, _key=_key)
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 793, in is_moving_domain
    if _corners_moved(first_wrfnc, ll_corner, ur_corner, lat_coord, lon_coord):
  File "/usr/local/lib/python3.8/dist-packages/wrf/util.py", line 663, in _corners_moved
    for i in py3range(lats.shape[-3]):
IndexError: tuple index out of range
```

 I also noticed I get exactly the same error when reading from multiple files, also with the meta data set to False. 
```
from wrf import  combine_files
import netCDF4 as nc
ncfile = nc.MFDataset('/WRFoutData/2015010100/wrfout_d03_2015-01-01_06*')
QRAIN = combine_files(ncfile, "QRAIN", timeidx="ALL_TIMES", method= "join", meta="False")
```
Which outputs the same error message as above.

**Comment by michaelavs** [comment]
I'm going to take a deeper look into what may be causing this, because it is reminding me of another wrfout file that was not working correctly when read in via xarray but would be fine when using wrf-python. In the mean time, I'm not sure if this is what you are attempting to do, but the wrf-python read the docs website does [have a section](https://wrf-python.readthedocs.io/en/latest/basic_usage.html?highlight=getvar#disabling-xarray-and-metadata) on disabling xarray and setting meta=False. It makes me think you may just be missing a step in the process, but, I am not completely sure at this moment. Let me know if that resource works or is helpful, otherwise, I will continue looking into this and try to update with any new ideas.

**Comment by michaelavs** [comment]
@CameronMcAinsh 
Sorry for not being active on this issue, but I recently came back to it and was wondering if you had found any success with it? I've been trying to recreate the issue with a wrfout file I have locally and if you haven't found a resolution yet, I wanted to check a couple of things with your file. If you have found a resolution, would you mind providing it here? I will then be able to resolve this issue as complete. 

Thank you!

**Comment by Gabrielsvc** [comment]
Hi @michaelavs !

I've been running into the same problem, but my situation is a little different. I have a wrfout file which has hourly data for a month and I'm trying to get the windspeed for it at a height level. My code was working fine with the file but i selected a smaller sample of 5 timesteps with cdo seltimestep.

The new generated file is using the XTIME variable and I encounter the same error when running 
`ht = getvar(ds_in, 'height_agl')`

Here is the wrfout file with the 5 time steps, if you want to check it out [wrfout_d02_2006-02-01_00-05](https://drive.google.com/file/d/1V_V6Q-Fvek5SlQEWPzviajgVHALbILVY/view?usp=sharing)

**Comment by michaelavs** [comment]
Hi @Gabrielsvc,
Can you run a ```print(ds_in)``` on the unmodified, all time step wrfout file and paste a screenshot of the top portion here? I have a couple of theories about what may be causing the issue, but want to make a couple of comparisons between the file that worked (before subsetting if I'm not mistaken), and the file that doesn't work (after subsetting). The theories I have right now are based on comparison to the file you provided and a file that I have locally, but they are as follows:
1. cdo seltimestep is adding metadata that cannot be processed correctly by wrf-python which is why it only runs when meta=False
2. the wrf version you are using is a newer version than wrf-python supports (I can't find anything so far to support this theory though)

I don't think XTIME is actually the culprit here, as it just represents that TIME is in an xarray.DataArray format and also works with the other files I have locally. When meta=False, the returned array is numpy.ndarray and not an xarray.DataArray, and no longer stores the meta data like Coordinates, Dimensions without coordinates, or Attributes. For example, when I ran my local file with meta=false, the only output was height_agl values, when I ran my local file with meta=True, I now see the data labels at the top and the metadata below the height_agl values. So, I think the issue is most likely coming from theory 1, but again I want to make a couple of comparisons between the two files before resolving that is the case.

**Comment by Gabrielsvc** [comment]
When you say top portion, you mean the attributes of the `ds_in` file, right? Sure can! Attached is the full output. Here you go:
`<stdin>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.                                                                                                                                                                                       <class 'netCDF4._netCDF4.Dataset'>                                                                                                                                                                                                                                    root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):                                                                                                                                                                                                        TITLE:  OUTPUT FROM WRF V4.2.2 MODEL                                                                                                                                                                                                                                  START_DATE: 2006-02-01_00:00:00                                                                                                                                                                                                                                       SIMULATION_START_DATE: 2006-02-01_00:00:00                                                                                                                                                                                                                            WEST-EAST_GRID_DIMENSION: 256                                                                                                                                                                                                                                     
    SOUTH-NORTH_GRID_DIMENSION: 181                                                                                                                                                                                                                                   
    BOTTOM-TOP_GRID_DIMENSION: 33                                                                                                                                                                                                                                     
    DX: 5000.0
    DY: 5000.0
    AERCU_OPT: 0
    AERCU_FCT: 1.0
    IDEAL_CASE: 0
    DIFF_6TH_SLOPEOPT: 0
    AUTO_LEVELS_OPT: 2
    DIFF_6TH_THRESH: 0.1
    DZBOT: 50.0
    DZSTRETCH_S: 1.3
    DZSTRETCH_U: 1.1
    SKEBS_ON: 0
    SPEC_BDY_FINAL_MU: 1
    USE_Q_DIABATIC: 0
    GRIDTYPE: C
    DIFF_OPT: 1
    KM_OPT: 4
    DAMP_OPT: 0
    DAMPCOEF: 0.15
    KHDIF: 0.0
    KVDIF: 0.0
    MP_PHYSICS: 4
    RA_LW_PHYSICS: 4
...
[filename.txt](https://github.com/NCAR/wrf-python/files/6586461/filename.txt)

`

It's driving me crazy that running any command on cdo is seamless and easy, and trying to handle the data with python and netCDF4 is so mind boggling. I will try to run `getvar` with `meta=False` and see if it solves the problem for me. Thanks for the quick reply!

**Comment by michaelavs** [comment]
So a couple of things:
1. You can subset a specific range of time indexes by using something like:
```
wrfin = Dataset(file_path)
var = getvar(wrfin, 'height_agl', timeidx=ALL_TIMES) 
var_subset = var[0:2] # Time step 1 and 2 are selected here. For, say, the first 5 steps, it would be [0:5]
```
and all metadata is preserved in this route. 

2. Can you provide the file and the code you are using to read in the dataset with? On my side, the subset data was able to run when meta=False. I'm not sure why it isn't liking when you run it so I want to make sure all aspects are the same between my test code and your code. Are you using either xarray or netCDF4 to read in the dataset? This may be where the problem is coming from if you aren't, but this is just another thought/possibility that I won't know for sure without seeing your first couple lines of code.

3. It does appear that  there is some additional reformatting occurring with cdo seltimestep. If you look at the print out of the subsetted dataset, at the top, there is information about how/when/where the dataset was subsetted using cdo seltimestep. In the non-subset, this information doesn't exist.

**Comment by Gabrielsvc** [comment]
1.  I'm my case i didn't subset the variable since the original file was too big, and loading the data would take too long, or get the process killed. For that I've applied the same idea of the "Performance tips" section in the wrf-python docs.

2. Here is the code I'm using. The data read is done with netCDF4 
[read-load.zip](https://github.com/NCAR/wrf-python/files/6592243/read-load.zip)

3. I'm going to take another look at the attributes of both files, it seems to be the case. When checking with ncview both files, the time dimension of the subset shows the correct data formated (i.e. 01-february-2006) while in the original nc file, the time dimension is just integers (i.e. 1, 2, ..., 744)

**Comment by colinmaxime** [comment]
I'm having a similar issue with wrf-python. Did anyone find a solution ?

The end of the traceback gives:
  File "/home/.../.conda/envs/conda_..._1/lib/python3.10/site-packages/wrf/util.py", line 664, in _corners_moved
    for i in py3range(lats.shape[-3]):
IndexError: tuple index out of range

The line that creates the issue is:
z_get_raw      = wrf.getvar(ifile, "z",       timeidx=wrf.ALL_TIMES, meta=True)

Each file that I'm analysing is a daily average of a wrfout file, computed by CDO. Each of the wrfout files contains a different number of times (files have different sizes), but they all start at 5am on the relevant day, and they all contain hourly output. 

Any clue on what's going on, and on how to fix this ? Thanks a lot.
