### ISSUE TITLE
Extract altitude of layer boundaries

### ISSUE THREAD

**Issue by andreas-h** [NCAR/wrf-python#20]
Currently, the `z` diagnostic returns the "full model height".  Is this the altitude of the layer midpoint or of the layer top?  This should be clarified in the documentation.

On this note, in case `z` returns the layer midpoint, it would be useful to also have the layer interfaces available.

**Comment by bladwig1** [comment]
The getvar routine always returns the diagnostic on the mass grid (center of grid box).  To get the heights on the vertical staggered grid, you just do:

(PH + PHB) / Constants.G

**Comment by andreas-h** [comment]
Thanks for the clarification!  Would you be open to a pull request implementing this as an additional diagnostic?  If so, what should it be called?

**Comment by bladwig1** [comment]
Generally in NCL and wrf-python, we've left the staggered grid stuff out of the 'getvar' routines because there's no need to run any de-staggering on the arrays.  But, there are probably many users that would like to get the full eta levels easily.  Thank you for offering to do a pull request, but since I'm already knee deep in the 1.1 changes and the code is in a bit of disarray, I will probably just sneak this quick change in myself.
