### ISSUE TITLE
Memory leak appears in the function wrf.getvar

### ISSUE THREAD

**Issue by wqshen** [NCAR/wrf-python#5]
Today, i use the wrf-python to process my wrfout files, and loop to read variable and do some calculations, the code as follow is just a demo, for some reasons, i have to open same wrfout file many times, it doesn't matter for specifying the `timeidx` argument, but need a bigger sized wrfout file  to reproduce this problem

```python
from netCDF4 import Dataset
import wrf

for i in range(150):
    f = Dataset('wrfout_d01_2005-07-17_12_00_00.nc')
    p = wrf.getvar(f, 'pressure')
    f.close()
```

I use `top` to see the memory change, and found the used memory by my program continues to increase.

Finally, i found these memory leak can be linked to the Decorator in the wrf/pressure.py
```@copy_and_set_metadata(copy_varname=either("P", "PRES"), name="pressure",                  description="pressure")``` for pressure variables.
If disable the xarray by using wrf.disable_xarray(), this memory leak question disappeared.

with following code, one can see the difference between enabled and disabled xarray
```python
from netCDF4 import Dataset
import wrf
from multiprocessing import Pool

def do(jobid):
    if jobid == 1:
        wrf.disable_xarray()
    for i in range(150):
        f = Dataset('wrfout_d01_2005-07-17_12_00_00.nc')
        slp = wrf.getvar(f, 'slp')
        f.close()

pool = Pool(2)
pool.map(do, [0, 1])
pool.close()
pool.join()
```
![memoryleakofwrf-python](https://cloud.githubusercontent.com/assets/12339722/23737611/28dc0d0e-04cf-11e7-9aac-1cb9e3a891c2.png)

I think the Decorator function ```copy_and_set_metadata``` in the wrf/metadecorators.py maybe need to revise, though i still do not know the reason for raising this question.

**Comment by bladwig1** [comment]
Thank you for the feedback.  Are you able to share your data file with me?  I don't have any WRF files with that many time steps in them, so I'm unable to see the problem.  If the file isn't too gigantic, you can follow the FTP instructions here:

http://www.ncl.ucar.edu/report_bug.shtml

and let me know the name of the file you uploaded.  Otherwise, you can send me a sharable dropbox, amazon, or google link to the file.  

Thanks!

**Comment by bladwig1** [comment]
When xarray is enabled, there is an internal thread-safe cache used to hold the XLAT and XLONG coordinate variables, along with a boolean variable to remember if a particular file or sequence is from a moving nest.  This is useful when working with sequences of WRF files, so that the XLAT and XLONG variables aren't repeatedly extracted.  This cache is limited to holding 20 items, and the key is the file or sequence of files object ID.    In your test, since you are creating a new file object each time, you're going to fill up those 20 cache spots.  There is a function set_cache_size() that can be used to decrease the number of coordinate variables that are cached (it needs to be called before your tests).  However, you currently can't set the cache size to 0 to turn it off, but I'll be putting in a fix for that soon.  I suspect you may be seeing the impact of this caching.  You should see it mostly top off after running your test cases a few times.

Also, top is not my favorite way to check memory usage on Linux, since you'll also see the buffer cache from disk IO.  If you can run 'free -m' and look at the -/+ buffers/cache line, you'll get an idea of what is being used by the running software on the system.  However, this is for the entire system, so it's not helpful if a lot of things are running.  If the rest of your system is mostly idle, then you should get a good estimate of how much memory has increased, and hopefully it's the size of XLAT and XLONG (x 20).  Keep in mind that python uses memory pools, so this probably isn't going to be exact. 

All that being said, I'm still not ruling out a bug on my end, so I'll play around with it some more.

**Comment by hhuangwx** [comment]
Thanks for resolving my confusion.
