### ISSUE TITLE
wrf interpolation returning nan or fill value

### ISSUE THREAD

**Issue by ameanijon** [NCAR/wrf-python#64]
I'm trying to interpolate relative humidity to the level 100mb less than the surface pressure. I wasn't sure whether to use wrf.interplevel or wrf.interpz3d, so I tried both:

```
rp = wrf.interplevel(mbl100r, current_pressure, sfc_pressure - 10000)
print rp.max()
print rp.min()
```
The above returns nan, below returns fill value

```
rp = wrf.interpz3d(mbl100r, current_pressure, sfc_pressure - 10000)
print rp.max()
print rp.min()
```

Relative humidity, current pressure and surface pressure are all 3d xarray

**Comment by bladwig1** [comment]
To be honest, I'm surprised this runs, since the 'desired level' parameter can only be a single value, but you're providing an array. If you really have a 2D array of surface pressure values and want to interpolate a 3D variable to some value that's 100 mb less than the surface pressure at each grid point, then at this time, your only option is to iterate over each grid point and call the interp1d function (http://wrf-python.readthedocs.io/en/latest/user_api/generated/wrf.interp1d.html#wrf.interp1d). It's not going to be particularly fast, but hopefully isn't too painful. 

In the future, interplevel (and interpz3d) will be modified to accept a 2D input for the desired level, but it's not there yet.

**Comment by ameanijon** [comment]
@bladwig1 Ooh.. thank you for your help. I think I understand where I've gone wrong now, I'll give it another shot
