### ISSUE TITLE
Can no longer import wrf-python using Python 2.7 on Windows

### ISSUE THREAD

**Issue by moptis** [NCAR/wrf-python#76]
Hello, wrf-python has been working well until I updated the package through Conda. Now I'm getting the attached import error. If I manually add numpy.core.multiarray, then I get another error saying the 'fomp_enabled' module isn't available since the library ._wrffortran isn't found. Any thoughts?

![image](https://user-images.githubusercontent.com/32751681/48074899-2d3fb680-e19f-11e8-9d07-3af611c0e2b7.png)

**Comment by bladwig1** [comment]
It looks like you've installed this to a root anaconda environment, and mixing anaconda packages with conda-forge packages can lead to bad things. Windows doesn't do a good job of reporting problems with extension modules. We strongly recommend using conda environments, particularly if you are using anaconda with conda-forge packages.

Can you please try installing wrf-python to a conda environment to see if that fixes your problem, since I am unable to reproduce the problem.

```
conda create -n wrf_env -c conda-forge wrf-python python=2.7
conda activate wrf_env (or activate wrf_env if your conda is old)
python
>>> import wrf
```

You can install any other packages that you need in to this environment from the conda-forge channel. It has everything that anaconda does.

Let me know if this fixes it.

**Comment by moptis** [comment]
Thanks @bladwig1 I'll give it a shot.
