### ISSUE TITLE
`getvar` doesn't work for geo files

### ISSUE THREAD

**Issue by andreas-h** [NCAR/wrf-python#8]
I'm not sure if the `getvar` function is supposed to work with the geogrid output, but for me currently it doesn't:  The geogrid output files contain `0000-00-00_00:00:00` as time, and `getvar` (obviously) cannot convert this.

Would it make sense to add a fix to `getvar`, so that in case the times cannot be converted, some magic happens?

**Comment by bladwig1** [comment]
For basic variable extraction, getvar should still work.  Obviously, most of the diagnostics calculations will fail since the variables needed aren't in there.  As for times, it should probably do something better than throw out a ValueError, but I'll need to think about it.  Numpy has a 'NaT', which might make the most sense here.

**Comment by bladwig1** [comment]
Actually, getvar is going to fail if meta is True, since the time parsing is failing.  It will work if meta is set to False.
